### PR TITLE
Unbundling tinyxml2

### PR DESCRIPTION
**Pull request by LyesSaadi**
This PR unbundles tinyxml and upgrade it to 7.0.0. I am not sure whether you're interested in it or not, but, either way, it is a requirement for Fedora & some other Linux distribution packaging, so there it is!

I have no idea how to write CMake build files, so if you are interested in this PR, please add it as a dependency there as well.

### CODE REVIEW

**Comment by PikachuHy** [comment]
I will write CMake build files later.

**Comment by NanoMichael** [comment]
The `meson.build` file needs to be fixed.

**Comment by PikachuHy** [comment]
> meson.build:6:0: ERROR: Dependency "tinyxml2" not found, tried pkgconfig and cmake

**Comment by PikachuHy** [comment]
ci may need to install dependency first.

**Comment by LyesSaadi** [comment]
> ci may need to install dependency first.

Yeah, sorry, I forgot there was a CI ^.^ !

> The `meson.build` file needs to be fixed.

It was already fixed, I just forgot to add libtinyxml2-dev as a dependency :P !

**Pull request merged**
