### PR TITLE
Major Meson improvements (for openmath)

### PR DESCRIPTION
**Pull request by sp1ritCS**
- Each directory now has it's own meson.build
- Now targeting "openmath"
- Seamless integration with the tests/

### CODE REVIEW

**Comment by sp1ritCS** [comment]
I've tried to implement building for qt5 aswell (with mesons qt5 module), but the support for qt5 is broken even with cmake.

I don't know how exactly building for qt5 works, but I hate it. The preprocessor (moc) "notes" that it doesn't find any relevant classes and thus generates an empty source file 🙃 which in turn causes gcc to fail because it is unable to find vtable MainWindow...

Maybe @jeremysanders and/or @Alexxey593 (dunno who is responsible for the qt impl) wants to take a look at this?

If you have access to a computer that can compile against win32 it would be great if you could add the gdi impl to meson.

**Comment by NanoMichael** [comment]
I'm not familiar with Qt, maybe @jeremysanders or @Alexxey593 wants to take a look?

This pull request could be merged.

**Comment by Alexxey593** [comment]
I was able to build it with CMake for Qt 5.12.10.
Also I'm able to build it with QMake (not committed yet).
But I have never used meson...

**Comment by NanoMichael** [comment]
Screenshot from 2021-03-18 23-39-27
I was able to build it with CMake for Qt 5 use the `openmath` branch and looks OK. I was merged the `master` branch into the `openmath` branch so that the #56 PR was applied, @sp1ritCS maybe you want to take a look?

**Comment by sp1ritCS** [comment]
I've gave it a shot, but it still doesn't work ._.

```
[98/98] Linking target src/clatexmath
FAILED: src/clatexmath 
c++  -o src/clatexmath src/clatexmath.p/meson-generated_moc_qt_mainwindow.cpp.o src/clatexmath.p/meson-generated_moc_qt_texwidget.cpp.o src/clatexmath.p/samples_qt_main.cpp.o src/clatexmath.p/samples_qt_texwidget.cpp.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group src/libclatexmath.so.0.0.4 -lQt5Core -lQt5Gui -lQt5Core -lQt5Widgets -lQt5Gui -lQt5Core -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/home/admin/workspace/apps/cLaTeXMath/_build/src
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: src/clatexmath.p/samples_qt_main.cpp.o: in function `main.cold':
qt_main.cpp:(.text.unlikely+0x2b): undefined reference to `vtable for MainWindow'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: src/clatexmath.p/samples_qt_main.cpp.o: in function `main':
qt_main.cpp:(.text.startup+0x7c): undefined reference to `MainWindow::MainWindow(QWidget*)'
/usr/lib64/gcc/x86_64-suse-linux/10/../../../../x86_64-suse-linux/bin/ld: qt_main.cpp:(.text.startup+0x98): undefined reference to `vtable for MainWindow'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

qt moc still just generates an empty file (check `_build/src/clatexmath.p/{moc_qt_mainwindow.cpp,moc_qt_texwidget.cpp,qt_mainwindow.moc}` that compile to a 1000 bytes binary just containing
```
ELF>h@@
	GCC: (SUSE Linux) 10.2.1 20210303 [revision 85977f624a34eac309f9d77a58164553dfc82975] GNUmoc_qt_mainwindow.cpp.symtab.strtab.shstrtab.text.data.bss.comment.note.GNU-stack.note.gnu.property@!@@,0@W5E0X[EOF]
``` 
(`_build/src/clatexmath.p/meson-generated_moc_qt_{mainwindow,texwidget}.cpp.o`)
but that is obviously expected from an empty c/++ file

Here is a diff of what I've done.
[qt.diff.gz](https://github.com/NanoMichael/cLaTeXMath/files/6166461/qt.diff.gz)

Compile instructions:
```sh
meson _build -DTARGET_DEMO=QT
ninja -C _build/
```

I don't know how the [meson qt5 module](https://mesonbuild.com/Qt5-module.html) and especially qt5.preprocess/moc works. So If someone knows it better than me, please give it a shot.

**Comment by Alexxey593** [comment]
What is the purpose of "openmath" branch? Should I use it or master branch?

**Comment by NanoMichael** [comment]
@Alexxey593 The `openmath` branch is to support the Unicode-math feature and now in development and not yet released, the `master` will be deprecated when the `openmath` was released.

**Pull request merged**
