### PR TITLE
Use macro instead of configure file, fix for msvc

### PR DESCRIPTION
**Pull request by Xrysnow**

### CODE REVIEW

**Comment by Xrysnow** [comment]
Related to #49.
@sp1ritCS you can try if this works for you.

**Comment by sp1ritCS** [comment]
Breaks https://github.com/blackhole89/notekit with:
```
../mainwindow.cpp: In constructor 'CMainWindow::CMainWindow(const Glib::RefPtr<Gtk::Application>&)':
../mainwindow.cpp:28:2: error: 'LaTeX' has not been declared
  LaTeX::init((data_path+"/data/latex").c_str());
  ^~~~~
../mainwindow.cpp:30:2: error: 'TeXRender' was not declared in this scope
  TeXRender *r = LaTeX::parse(utf82wide("\\fatalIfCmdConflict{false}"),1,1,1,0);
  ^~~~~~~~~
../mainwindow.cpp:30:2: note: suggested alternative:
In file included from /usr/local/include/clatexmath/latex.h:7:0,
                 from ../mainwindow.cpp:8:
/usr/local/include/clatexmath/render.h:13:7: note:   'tex::TeXRender'
 class TeXRender {
       ^~~~~~~~~
../mainwindow.cpp:30:13: error: 'r' was not declared in this scope
  TeXRender *r = LaTeX::parse(utf82wide("\\fatalIfCmdConflict{false}"),1,1,1,0);
             ^
../mainwindow.cpp:30:17: error: 'LaTeX' has not been declared
  TeXRender *r = LaTeX::parse(utf82wide("\\fatalIfCmdConflict{false}"),1,1,1,0);
                 ^~~~~
../mainwindow.cpp:30:30: error: 'utf82wide' was not declared in this scope
  TeXRender *r = LaTeX::parse(utf82wide("\\fatalIfCmdConflict{false}"),1,1,1,0);
                              ^~~~~~~~~
../mainwindow.cpp:30:30: note: suggested alternative:
In file included from /usr/local/include/clatexmath/common.h:31:0,
                 from /usr/local/include/clatexmath/latex.h:4,
                 from ../mainwindow.cpp:8:
/usr/local/include/clatexmath/utils/utf.h:78:21: note:   'tex::utf82wide'
 inline std::wstring utf82wide(const char* in) {
                     ^~~~~~~~~
../mainwindow.cpp:31:15: error: type '<type error>' argument given to 'delete', expected pointer
  if(r) delete r;
               ^
```

on ubuntu:18.04 via podman.

**Comment by Xrysnow** [comment]
> Please bump the soverion aswell as the minorverision in the meson file.

@sp1ritCS Do you mean change the version here to `0.0.3`?
https://github.com/NanoMichael/cLaTeXMath/blob/2dd810dcb7d58c81d3fd7c304cc39296f3bd0c56/meson.build#L1-L4

**Comment by sp1ritCS** [comment]
@Xrysnow no, thats the patch version. It shuld be irrelevant for projects that link against it. 

The minior version is 0.**M**.0 fixes that break projects that link againsr clatexmath, but that can be easily fixed should have a bumped minor version.

Big changes, that require a lot of work from projects that link against clatexmath, should have an updated major version.

Changes, that break the compiled shared object  in comparison to a earlier release, should have a bumped soversion. (Further down in the meson.build, by pkgxonfig) - but I don't know if this is the case here

**Comment by Xrysnow** [comment]
@NanoMichael I think it's ok to merge this PR.
@sp1ritCS you can change the version number after merged.

**Comment by sp1ritCS** [comment]
Any reason why you don't add it now?

**Comment by Xrysnow** [comment]
I'm not sure what change you need, so you can add it by yourself.

**Comment by sp1ritCS** [comment]
Me neither - at least bump the minor version. Otherwise it shouldn't merged to master

**Comment by Xrysnow** [comment]
OK, now it's changed.

**Comment by sp1ritCS** [comment]
LGTM

**Comment by NanoMichael** [comment]
I see your comments, now I think it is OK to merge.

**Pull request merged**
