### PR TITLE
Minor improvement for openmath

### PR DESCRIPTION
**Pull request by PikachuHy**
- use `logv` replace `print`
- fix latex2png build fail
- remove warning

### CODE REVIEW

**Comment by NanoMichael** [comment]
> ???

It seems I have the same modification for this improvement but not pushed, waiting for me to confirm.

**Comment by PikachuHy** [comment]
Are all the codes pushed?

**Comment by PikachuHy** [comment]
???

**Comment by NanoMichael** [comment]
> ???

Sorry for the late response, merged now 😄

**Comment by PikachuHy** [comment]
thanks

**Pull request merged**
